<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

# 01.品种鉴定——K最近邻

In [5]:
import numpy as np
import pandas as pd
import mglearn

In [22]:
ori_df = pd.read_table('data_for_ml', header = None, sep=' ')

In [54]:
all_features = ori_df.iloc[:, 1:].values
all_features

array([[1, 1, 2, ..., 1, 1, 0],
       [1, 2, 1, ..., 0, 0, 0],
       [0, 2, 2, ..., 0, 1, 1],
       ...,
       [2, 1, 1, ..., 2, 1, 1],
       [1, 0, 0, ..., 2, 2, 2],
       [0, 0, 1, ..., 2, 1, 1]], dtype=int64)

In [39]:
all_labels = ori_df.iloc[:, :1].values.ravel()
all_labels

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
        9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10

In [40]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split( 
    all_features, all_labels, random_state=0)

In [41]:
print("X_train shape: {}".format(X_train.shape)) 
print("y_train shape: {}".format(y_train.shape))

X_train shape: (171, 767)
y_train shape: (171,)


In [42]:
print("X_test shape: {}".format(X_test.shape)) 
print("y_test shape: {}".format(y_test.shape))

X_test shape: (57, 767)
y_test shape: (57,)


In [43]:
# n_neighbors=1
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors=1)

In [44]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [45]:
y_pred = knn.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [ 5  9  6  9  7  2 10  4 10  8  5  2  7  1  6  5  2  1  2  8  8  2 10 10
  2  3  3  2  1  5  8  5  9  3  5  1  1  8  1  2 10  2  5  3 10  9  2  3
  5  9  2  7  9  4  1  5  2]


In [46]:
print("Test set score: {:.2f}".format(np.mean(y_pred == y_test)))

Test set score: 0.65


In [47]:
# n_neighbors=3
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [48]:
y_pred = knn.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [ 5  9  6  9  7  2 10  4 10  8  5  2  7  1  6  5  2  1  2  8  8  2  6 10
  2  3  3  2  1  5  8  5  9  3  5  1  1  8  1  2 10  2  5  3 10  9  2  3
  5  9  2  2  9  4  1  5  2]


In [51]:
print("Test set score: {:.4f}".format(np.mean(y_pred == y_test)))

Test set score: 0.6140


In [52]:
# n_neighbors=3
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
print("Test set score: {:.4f}".format(np.mean(y_pred == y_test)))

Test set score: 0.6140


In [64]:
# 只用两个品种
two_breeds_features = ori_df.iloc[:51, 1:].values
two_breeds_features.shape

(51, 767)

In [66]:
two_breeds_labels = ori_df.iloc[:51, :1].values.ravel()
two_breeds_labels.shape

(51,)

In [67]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split( 
    two_breeds_features, two_breeds_labels, random_state=0)

In [68]:
print("X_train shape: {}".format(X_train.shape)) 
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape)) 
print("y_test shape: {}".format(y_test.shape))

X_train shape: (38, 767)
y_train shape: (38,)
X_test shape: (13, 767)
y_test shape: (13,)


In [69]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors=1)

In [71]:
knn.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=1)

In [72]:
y_pred = knn.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))

Test set predictions:
 [2 1 1 1 1 2 2 2 2 1 2 2 2]


In [73]:
print("Test set score: {:.4f}".format(np.mean(y_pred == y_test)))

Test set score: 1.0000


In [85]:
# 用YHC和ZTC两个品种
two_breeds_features = ori_df.iloc[184:227, 1:].values
two_breeds_labels = ori_df.iloc[184:227, :1].values.ravel()
print(two_breeds_features.shape, two_breeds_labels.shape)


(43, 767) (43,)


In [86]:
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split( 
    two_breeds_features, two_breeds_labels, random_state=0)
print("X_train shape: {}".format(X_train.shape)) 
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape)) 
print("y_test shape: {}".format(y_test.shape))

X_train shape: (32, 767)
y_train shape: (32,)
X_test shape: (11, 767)
y_test shape: (11,)


In [89]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [90]:
y_pred = knn.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))
print("Test set score: {:.4f}".format(np.mean(y_pred == y_test)))

Test set predictions:
 [10 10 10  9  9 10 10  9 10 10 10]
Test set score: 1.0000
