<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

# 02.品种鉴定——朴素贝叶斯

In [33]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix 
from sklearn.naive_bayes import GaussianNB
import matplotlib.pyplot as plt 
#import mglearn

In [2]:
# 读取数据
ori_df = pd.read_table('data_for_ml', header = None, sep=' ')
all_features = ori_df.iloc[:, 1:].values
all_labels = ori_df.iloc[:, :1].values.ravel()

In [17]:
# 数据分割
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split( 
    all_features, all_labels, random_state=0)
print("X_train shape: {}".format(X_train.shape)) 
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape)) 
print("y_test shape: {}".format(y_test.shape))

X_train shape: (171, 767)
y_train shape: (171,)
X_test shape: (57, 767)
y_test shape: (57,)


In [18]:
# train
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [21]:
# test
y_pred = gnb.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))
print("Test set score: {:.4f}".format(np.mean(y_pred == y_test)))
print("Confusion matrix:\n{}".format(confusion_matrix(y_test, y_pred)))

Test set predictions:
 [ 3  4  6  6  7  7 10  6 10  9  7  3  3  1  6  3  7  1  1  8  8  7 10 10
  7  3  6  2  1  3  9  3  6  3  7  6  3  8  6  7 10  3  7  6  3  9  7  3
  3  6  7  6  9  6  1  3  7]
Test set score: 0.4386
Confusion matrix:
[[4 0 1 0 0 2 0 0 0 0]
 [1 1 0 0 0 0 1 0 0 0]
 [0 0 4 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0]
 [0 0 2 0 0 0 8 0 0 0]
 [0 0 0 0 0 3 0 0 0 0]
 [0 0 6 0 0 2 3 0 0 0]
 [0 0 0 0 0 0 0 3 2 0]
 [0 0 0 1 0 3 0 0 2 0]
 [0 0 1 0 0 0 0 0 0 5]]


In [34]:
# 用YHC和ZTC两个品种
two_breeds_features = ori_df.iloc[184:227, 1:].values
two_breeds_labels = ori_df.iloc[184:227, :1].values.ravel()
print(two_breeds_features.shape, two_breeds_labels.shape)
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split( 
    two_breeds_features, two_breeds_labels, random_state=0)
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))
print("Test set score: {:.4f}".format(np.mean(y_pred == y_test)))

(43, 767) (43,)
Test set predictions:
 [10 10 10  9  9 10 10  9 10 10 10]
Test set score: 1.0000
