<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

# 03.品种鉴定——支持向量机 SVM

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix 
from sklearn.svm import SVC

In [4]:
# 读取数据
ori_df = pd.read_table('data_for_ml', header = None, sep=' ')
all_features = ori_df.iloc[:, 1:].values
all_labels = ori_df.iloc[:, :1].values.ravel()

In [3]:
# 数据分割
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split( 
    all_features, all_labels, random_state=0)
print("X_train shape: {}".format(X_train.shape)) 
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape)) 
print("y_test shape: {}".format(y_test.shape))

X_train shape: (171, 767)
y_train shape: (171,)
X_test shape: (57, 767)
y_test shape: (57,)


In [9]:
# train
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)
# test
y_pred = svc.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))
print("Test set score: {:.4f}".format(np.mean(y_pred == y_test)))
print("Confusion matrix:\n{}".format(confusion_matrix(y_test, y_pred)))

Test set predictions:
 [ 3  9  6  9  3  2 10  4 10  8  3  2  3  1  6  3  2  1  2  8  8  2 10 10
  2  3  6  2  1  3  8  3  9  3  2  1  1  8  1  2 10  2  3  6 10  9  2  3
  3  9  2  3  9  4  1  3  2]
Test set score: 0.6316
Confusion matrix:
[[ 7  0  0  0  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  0  0  0  0]
 [ 0  0 10  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  5  0  0]
 [ 0  0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0  0  6]]


In [11]:
# 调节超参数
from sklearn.svm import SVC
svc = SVC(kernel='rbf') #, C=10, gamma=10
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))
print("Test set score: {:.4f}".format(np.mean(y_pred == y_test)))
print("Confusion matrix:\n{}".format(confusion_matrix(y_test, y_pred)))

Test set predictions:
 [ 3  9  6  9  3  2 10  4 10  8  3  2  3  1  6  3  2  1  2  8  8  2 10 10
  2  3  6  2  1  3  8  3  9  3  2  1  1  8  1  2 10  2  3  6 10  9  2  3
  3  9  2  3  9  4  1  3  2]
Test set score: 0.6316
Confusion matrix:
[[ 7  0  0  0  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  0  0]
 [ 0  0  0  2  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  0  0  0  0]
 [ 0  0 10  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  5  0  0]
 [ 0  0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0  0  6]]


In [6]:
# 用YHC和ZTC两个品种
two_breeds_features = ori_df.iloc[184:227, 1:].values
two_breeds_labels = ori_df.iloc[184:227, :1].values.ravel()
print(two_breeds_features.shape, two_breeds_labels.shape)
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split( 
    two_breeds_features, two_breeds_labels, random_state=0)
from sklearn.svm import SVC
svc = SVC(kernel='rbf') #, C=10, gamma=10
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))
print("Test set score: {:.4f}".format(np.mean(y_pred == y_test)))
print("Accuracy on test set: {:.3f}".format(svc.score(X_test, y_test)))
print("Confusion matrix:\n{}".format(confusion_matrix(y_test, y_pred)))

(43, 767) (43,)
Test set predictions:
 [10 10 10  9  9 10 10  9 10 10 10]
Test set score: 1.0000
Accuracy on test set: 1.000
Confusion matrix:
[[3 0]
 [0 8]]
