<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

# 04.品种鉴定——决策树 DT

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix 
from sklearn.tree import DecisionTreeClassifier 

In [3]:
# 读取数据
ori_df = pd.read_table('data_for_ml', header = None, sep=' ')
all_features = ori_df.iloc[:, 1:].values
all_labels = ori_df.iloc[:, :1].values.ravel()

In [3]:
# 数据分割
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split( 
    all_features, all_labels, random_state=0)
print("X_train shape: {}".format(X_train.shape)) 
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape)) 
print("y_test shape: {}".format(y_test.shape))

X_train shape: (171, 767)
y_train shape: (171,)
X_test shape: (57, 767)
y_test shape: (57,)


In [6]:
from sklearn.tree import DecisionTreeClassifier 
tree = DecisionTreeClassifier(random_state=0) 
tree.fit(X_train, y_train) 
y_pred = tree.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))
print("Accuracy on training set: {:.3f}".format(tree.score(X_train, y_train))) 
print("Accuracy on test set: {:.3f}".format(tree.score(X_test, y_test)))
print("Confusion matrix:\n{}".format(confusion_matrix(y_test, y_pred)))

Test set predictions:
 [ 7  4  6  9  7  5  7  8  5  4  2  2  6  1  3  7  5  4  2  4  8  2  4 10
  7  3  7  2  3  2  4  7  9  3  5  2  2  8  1  1  7  5  2  3 10  4  2  3
  2  4  2  7  9  1  1  7  2]
Accuracy on training set: 1.000
Accuracy on test set: 0.491
Confusion matrix:
[[3 2 1 1 0 0 0 0 0 0]
 [0 3 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 1 0 0]
 [1 4 0 0 4 0 1 0 0 0]
 [0 0 2 0 0 1 0 0 0 0]
 [0 4 0 0 0 0 7 0 0 0]
 [0 0 0 3 0 0 0 2 0 0]
 [0 0 0 3 0 0 0 0 3 0]
 [0 0 0 1 1 0 2 0 0 2]]


In [7]:
tree = DecisionTreeClassifier(max_depth=4, random_state=0) 
tree.fit(X_train, y_train) 
y_pred = tree.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))
print("Accuracy on training set: {:.3f}".format(tree.score(X_train, y_train))) 
print("Accuracy on test set: {:.3f}".format(tree.score(X_test, y_test)))
print("Confusion matrix:\n{}".format(confusion_matrix(y_test, y_pred)))

Test set predictions:
 [ 7  4  3  9 10  5 10  4  2  8  2  2  3  1  3 10  3  4  2  8  8  2  4 10
  7  3  7  2  3  2  8 10  9  5  3  1  1  8  3  1  4  3  2  4 10  4  2  5
  2  4  2 10  9  1  1  7  2]
Accuracy on training set: 0.766
Accuracy on test set: 0.439
Confusion matrix:
[[4 0 2 1 0 0 0 0 0 0]
 [0 3 0 0 0 0 0 0 0 0]
 [0 0 2 0 2 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 4 3 0 1 0 1 0 0 0]
 [0 0 2 1 0 0 0 0 0 0]
 [0 4 0 0 0 0 3 0 0 4]
 [0 0 0 0 0 0 0 5 0 0]
 [0 0 0 3 0 0 0 0 3 0]
 [0 1 0 2 0 0 0 0 0 3]]


In [8]:
print("Feature importances:\n{}".format(tree.feature_importances_))

Feature importances:
[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.11731322 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0

决策树的泛化性能实在太差了，即使控制max_depth参数，在测试数据集上的准确性仍旧不到0.5。

In [4]:
# 用YHC和ZTC两个品种
two_breeds_features = ori_df.iloc[184:227, 1:].values
two_breeds_labels = ori_df.iloc[184:227, :1].values.ravel()
print(two_breeds_features.shape, two_breeds_labels.shape)
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split( 
    two_breeds_features, two_breeds_labels, random_state=0)
tree = DecisionTreeClassifier(max_depth=4, random_state=0) 
tree.fit(X_train, y_train) 
y_pred = tree.predict(X_test) 
print("Test set predictions:\n {}".format(y_pred))
print("Accuracy on training set: {:.3f}".format(tree.score(X_train, y_train))) 
print("Accuracy on test set: {:.3f}".format(tree.score(X_test, y_test)))
print("Confusion matrix:\n{}".format(confusion_matrix(y_test, y_pred)))

(43, 767) (43,)
Test set predictions:
 [10  9 10  9  9  9 10  9 10 10  9]
Accuracy on training set: 1.000
Accuracy on test set: 0.727
Confusion matrix:
[[3 0]
 [3 5]]
